global:
  scrape_interval: "10s"
  scrape_timeout: "5s"
  evaluation_interval: "1m"


scrape_configs:
  - job_name: scrape metric app from OTEL exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - "otel-collector:8889" # domain docker otel collector